// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Rubik } from "next/font/google";

import FooterComponent from "@/components/FooterComponent";
import NavigationComponent from "@/components/NavigationComponent";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className} antialiased`}>
        <div className="  min-w-full container mx-auto">
          {/* <NavbarComponent /> */}
          {/* <NavigationComponent /> */}

          {children}
        </div>
        {/* <FooterComponent /> */}
      </body>
    </html>
  );
}
