// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Rubik } from "next/font/google";

import CardComponent from "@/components/CardComponent";
import NavbarComponent from "@/components/NavbarComponent";
import ImgBoardComponent from "@/components/ImgBoardComponent";
import FooterComponent from "@/components/FooterComponent";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${rubik.variable} antialiased`}>
        <NavbarComponent />

        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
